export default [
    {
        img: "courses/1.jpg",
        fan: "Algebra",
        kun: "210",
        h4: "Algebra uchun yangi Kurs",
        p: "2023 yil mart oyidan boshlab o'quv markazi 2024 o'quv yili uchun Abituriyentlar uchun Algebra tayyorgarlik kursiga qabul qilinadi.",
        narxi: "$165.00",
        _id: "algebra",
        title: "Algebra",
    },
    {
        img: "courses/2.jpg",
        fan: "Fizika",
        kun: "210",
        h4: "Fizika uchun yangi Kurs",
        p: "2023 yil mart oyidan boshlab o'quv markazi 2024 o'quv yili uchun Abituriyentlar uchun Fizika tayyorgarlik kursiga qabul qilinadi.",
        narxi: "$165.00",
        _id: "fizika",
        title: "Fizika",
    },
    {
        img: "courses/3.jpg",
        fan: "Kimyo",
        kun: "210",
        h4: "Kimya uchun yangi Kurs",
        p: "2023 yil mart oyidan boshlab o'quv markazi 2024 o'quv yili uchun Abituriyentlar uchun Kimya tayyorgarlik kursiga qabul qilinadi.",
        narxi: "$165.00",
        _id: "kimyo",
        title:"Kimyo",
    },
    {
        img: "courses/4.jpg",
        fan: "Biologiya",
        kun: "102",
        h4: "Biologiya uchun yangi Kurs",
        p: "2023 yil mart oyidan boshlab o'quv markazi 2024 o'quv yili uchun Abituriyentlar uchun Biologiya tayyorgarlik kursiga qabul qilinadi.",
        narxi: "$165.00",
        _id: "giologiya",
        title: "Biologiya"
    },
    {
        img: "courses/5.jpg",
        fan: "Geografiya",
        kun: "75",
        h4: "Geografiya uchun yangi Kurs",
        p: "2023 yil mart oyidan boshlab o'quv markazi 2024 o'quv yili uchun Abituriyentlar uchun Geagrafiya tayyorgarlik kursiga qabul qilinadi.",
        narxi: "$165.00",
        _id: "geografiya",
        title:"Geografiya"
    },
    {
        img: "courses/6.jpg",
        fan: "Tarix",
        kun: "210",
        h4: "Tarix uchun yangi Kurs",
        p: "2023 yil mart oyidan boshlab o'quv markazi 2024 o'quv yili uchun Abituriyentlar uchun Tarix tayyorgarlik kursiga qabul qilinadi.",
        narxi: "$165.00",
        _id: "tarix",
        title:"Tarix"
    },
]