export default [
    {
        img: "expertteachers/1.jpg",
        fan: "Algebra",
        kun: "210",
        h4: "",
        p: "2023 yil mart oyidan boshlab o'quv markazi 2024 o'quv yili uchun Abituriyentlar uchun Algebra tayyorgarlik kursiga qabul qilinadi",
        narxi: "",
        _id: "algebrateachers",
        title:"Algebra",
    },
    {
        img: "expertteachers/2.jpg",
        fan: "Fizika",
        kun: "210",
        h4: "Fizika uchun yangi Kurs",
        p: "2023 yil mart oyidan boshlab o'quv markazi 2024 o'quv yili uchun Abituriyentlar uchun Fizika tayyorgarlik kursiga qabul qilinadi",
        narxi: "$165.00",
        _id: "fizikateachers",
        title:"Fizika",
        
    },
    {
        img: "expertteachers/3.jpg",
        fan: "Kimyo",
        kun: "210",
        h4: "Kimya uchun yangi Kurs",
        p: "2023 yil mart oyidan boshlab o'quv markazi 2024 o'quv yili uchun Abituriyentlar uchun Kimyo tayyorgarlik kursiga qabul qilinadi",
        narxi: "$165.00",
        _id: "kimyoteachers",
        title:"Kimyo",
      
    },
    {
        img: "expertteachers/4.jpg",
        fan: "Biologiya",
        kun: "102",
        h4: "Biologiya uchun yangi Kurs",
        p: "2023 yil mart oyidan boshlab o'quv markazi 2024 o'quv yili uchun Abituriyentlar uchun Biologiya tayyorgarlik kursiga qabul qilinadi",
        narxi: "$165.00",
        _id: "giologiyateachers",
        title:"Biologiya",
       
    },
    {
        img: "expertteachers/5.jpg",
        fan: "Geografiya",
        kun: "75",
        h4: "Geografiya uchun yangi Kurs",
        p: "2023 yil mart oyidan boshlab o'quv markazi 2024 o'quv yili uchun Abituriyentlar uchun Geagrafiya tayyorgarlik kursiga qabul qilinadi",
        narxi: "$165.00",
        _id: "geografiyateachers",
        title:"Geografiya",
       
    },
    {
        img: "expertteachers/6.jpg",
        fan: "Tarix",
        kun: "210",
        h4: "Tarix uchun yangi Kurs",
        p: "2023 yil mart oyidan boshlab o'quv markazi 2024 o'quv yili uchun Abituriyentlar uchun Tarix tayyorgarlik kursiga qabul qilinadi",
        narxi: "$165.00",
        _id: "tarixteachers",
        title: "Tarix", 
    },
]